Repository Tutor2Tutee/Tutor2Tutee, pull requests merged in 2021-06, with the labels that each got.

#32 fixed : issue #31
  servers/server.js
Labels: bug

#33 [Site] Added Responsiveness
  public/index.html
  src/client/Root.css
  src/component/Header/Header.css
  src/component/Header/Header.js
  src/component/Layout/Layout.js
  src/component/Nav/Nav.css
  src/component/Nav/Nav.js
  src/component/SideDrawer/SideDrawer.css
  src/component/SideDrawer/SideDrawer.js
  src/component/UI/NavLink/NavLinks.js
  src/pages/About/About.css
  src/pages/About/About.js
  src/pages/Auth/Login/Login.css
  src/pages/Auth/Signup/Signup.css
  src/pages/Feature/Feature.css
  src/pages/Home/Home.css
Labels: Frontend, enhancement

#34 [Site]Added Korean Support
  src/assets/translation.png
  src/client/Root.css
  src/component/Header/Header.css
  src/component/Header/Header.js
  src/component/Nav/Nav.css
  src/component/Nav/Nav.js
  src/component/SideDrawer/SideDrawer.css
  src/component/SideDrawer/SideDrawer.js
  src/index.js
  src/pages/About/About.js
  src/pages/Auth/Login/Login.js
  src/pages/Auth/Signup/Signup.js
  src/pages/Class/Class.js
  src/pages/Feature/Feature.js
  src/pages/Home/Home.js
  src/shared/ImgSrc.js
  src/store/actions/language.js
  src/store/reducers/language.js
Labels: Frontend, documentation, enhancement, help wanted

#35 [Site] Added language.json locale file
  src/locale/language.json
  src/pages/About/About.js
  src/pages/Auth/Login/Login.js
  src/pages/Auth/Signup/Signup.js
  src/pages/Class/Class.js
  src/pages/Feature/Feature.js
  src/pages/Home/Home.js
Labels: Frontend, enhancement

#38 added : issue #37
  servers/models/classSchema.js
  servers/routes/Class.js
  servers/routes/User.js
  servers/routes/index.js
Labels: enhancement

#41 [Site] Fixed Theme Toggle Button Responsiveness
  src/component/Header/Header.css
  src/component/Header/Header.js
  src/component/Nav/Nav.css
  src/component/SideDrawer/SideDrawer.css
  src/component/SideDrawer/SideDrawer.js
Labels: Frontend, documentation, enhancement
