Repository Tutor2Tutee/Tutor2Tutee, pull requests merged in 2021-05, with the labels that each got.

#1 클래스 스키마와 모든 클래스 확인
  servers/routes/Class.js
  servers/schemas/classSchema.js
  servers/server.js
Labels: enhancement

#16 added fetch t2t-token from localStorage and added styles
  src/components/Footer.js
  src/components/Header.js
  src/components/User/Login.js
  src/components/User/Logout.js
  src/components/User/Register.js
  src/routes/Home.js
  src/shared/App.js
Labels: enhancement

#14 CLASS CRUD
  servers/models/classSchema.js
  servers/routes/Class.js
  servers/routes/User.js
Labels: enhancement

#22 Deployment
  Procfile
  package-lock.json
  package.json
  servers/server.js
Labels: Backend, Frontend

#23 [Site] Updated Login and Register Page
  src/component/UI/InputField/InputField.css
  src/component/UI/InputField/InputField.js
  src/pages/Auth/Login/Login.css
  src/pages/Auth/Login/Login.js
  src/pages/Auth/Signup/Signup.css
  src/pages/Auth/Signup/Signup.js
  src/pages/Home/Home.css
  src/pages/Home/Home.js
  src/pages/index.js
  src/shared/App_Latest.js
Labels: Frontend

#25 [Site] Added Features Page
  src/assets/attendence.png
  src/assets/meeting.png
  src/assets/rating.png
  src/assets/recorded_video.png
  src/pages/Feature/Feature.css
  src/pages/Feature/Feature.js
  src/pages/index.js
  src/shared/App_Latest.js
  src/shared/ImgSrc.js
Labels: Frontend, documentation
